defmodule Artifacts.Accounts.Token do
  @moduledoc """
  AshAuthentication session tokens for `Artifacts.Accounts.User`
  (DESIGN.md's `Artifacts.Accounts` table). Every attribute and action
  (`get_token`, `store_token`, `revoke_token`, `revoke_jti`,
  `revoke_all_stored_for_subject`, `expunge_expired`, `expired`) is
  generated by the `AshAuthentication.TokenResource` extension.
  """

  use Ash.Resource,
    domain: Artifacts.Accounts,
    data_layer: AshPostgres.DataLayer,
    extensions: [AshAuthentication.TokenResource],
    authorizers: [Ash.Policy.Authorizer]

  postgres do
    table "tokens"
    repo Artifacts.Repo
  end

  policies do
    bypass AshAuthentication.Checks.AshAuthenticationInteraction do
      authorize_if always()
    end
  end
end
