defmodule Artifacts.Accounts.UserIdentity do
  @moduledoc """
  Stores Google's `iss`/`sub` claims for each linked account, required by
  the `AshAuthentication.Strategy.OAuth2.Verifier` for any OAuth2/OIDC
  strategy (only `iss`/`sub` stably identify a returning user; email alone
  does not). `register_with_google` still matches by email
  (`upsert_identity :unique_email`, DESIGN.md's documented simplification)
  — this resource is bookkeeping the verifier requires, not a second
  matching path. Every attribute and action is generated by the
  `AshAuthentication.UserIdentity` extension.
  """

  use Ash.Resource,
    domain: Artifacts.Accounts,
    data_layer: AshPostgres.DataLayer,
    extensions: [AshAuthentication.UserIdentity]

  user_identity do
    user_resource Artifacts.Accounts.User
  end

  postgres do
    table "user_identities"
    repo Artifacts.Repo
  end
end
