defmodule Artifacts.Repo.Migrations.InitialAccounts do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:agent_keys, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :name, :text, null: false
      add :api_key_hash, :binary, null: false
      add :expires_at, :utc_datetime_usec, null: false
      add :revoked_at, :utc_datetime_usec
      add :agent_id, :uuid, null: false
    end

    create unique_index(:agent_keys, [:api_key_hash], name: "agent_keys_unique_api_key_index")

    create table(:agents, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:agent_keys) do
      modify :agent_id,
             references(:agents,
               column: :id,
               name: "agent_keys_agent_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:agents) do
      add :name, :text, null: false
      add :organization_id, :uuid, null: false
    end

    create table(:harnesses, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :name, :text, null: false
      add :api_key_hash, :binary, null: false
      add :expires_at, :utc_datetime_usec, null: false
      add :revoked_at, :utc_datetime_usec
      add :user_id, :uuid, null: false
    end

    create unique_index(:harnesses, [:api_key_hash], name: "harnesses_unique_api_key_index")

    create table(:memberships, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :user_id, :uuid, null: false
      add :organization_id, :uuid, null: false
    end

    create unique_index(:memberships, [:user_id, :organization_id],
             name: "memberships_unique_membership_index"
           )

    create table(:organizations, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:agents) do
      modify :organization_id,
             references(:organizations,
               column: :id,
               name: "agents_organization_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:memberships) do
      modify :organization_id,
             references(:organizations,
               column: :id,
               name: "memberships_organization_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:organizations) do
      add :name, :text, null: false
    end

    create table(:tokens, primary_key: false) do
      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :created_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :extra_data, :map
      add :purpose, :text, null: false
      add :expires_at, :utc_datetime, null: false
      add :subject, :text, null: false
      add :jti, :text, null: false, primary_key: true
    end

    create table(:user_identities, primary_key: false) do
      add :refresh_token, :text
      add :access_token_expires_at, :utc_datetime_usec
      add :access_token, :text
      add :uid, :text, null: false
      add :strategy, :text, null: false
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :user_id, :uuid
    end

    create unique_index(:user_identities, [:strategy, :uid],
             name: "user_identities_unique_on_strategy_and_uid_index"
           )

    create table(:users, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:harnesses) do
      modify :user_id,
             references(:users,
               column: :id,
               name: "harnesses_user_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:memberships) do
      modify :user_id,
             references(:users,
               column: :id,
               name: "memberships_user_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:user_identities) do
      modify :user_id,
             references(:users,
               column: :id,
               name: "user_identities_user_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:users) do
      add :email, :citext, null: false
      add :name, :text

      add :personal_organization_id,
          references(:organizations,
            column: :id,
            name: "users_personal_organization_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end

    create unique_index(:users, [:email], name: "users_unique_email_index")
  end

  def down do
    drop constraint(:users, "users_personal_organization_id_fkey")

    drop_if_exists unique_index(:users, [:email], name: "users_unique_email_index")

    alter table(:users) do
      remove :personal_organization_id
      remove :name
      remove :email
    end

    drop constraint(:user_identities, "user_identities_user_id_fkey")

    alter table(:user_identities) do
      modify :user_id, :uuid
    end

    drop constraint(:memberships, "memberships_organization_id_fkey")

    drop constraint(:memberships, "memberships_user_id_fkey")

    alter table(:memberships) do
      modify :user_id, :uuid
    end

    drop constraint(:harnesses, "harnesses_user_id_fkey")

    alter table(:harnesses) do
      modify :user_id, :uuid
    end

    drop table(:users)

    drop_if_exists unique_index(:user_identities, [:strategy, :uid],
                     name: "user_identities_unique_on_strategy_and_uid_index"
                   )

    drop table(:user_identities)

    drop table(:tokens)

    alter table(:organizations) do
      remove :name
    end

    alter table(:memberships) do
      modify :organization_id, :uuid
    end

    drop constraint(:agents, "agents_organization_id_fkey")

    alter table(:agents) do
      modify :organization_id, :uuid
    end

    drop table(:organizations)

    drop_if_exists unique_index(:memberships, [:user_id, :organization_id],
                     name: "memberships_unique_membership_index"
                   )

    drop table(:memberships)

    drop_if_exists unique_index(:harnesses, [:api_key_hash],
                     name: "harnesses_unique_api_key_index"
                   )

    drop table(:harnesses)

    alter table(:agents) do
      remove :organization_id
      remove :name
    end

    drop constraint(:agent_keys, "agent_keys_agent_id_fkey")

    alter table(:agent_keys) do
      modify :agent_id, :uuid
    end

    drop table(:agents)

    drop_if_exists unique_index(:agent_keys, [:api_key_hash],
                     name: "agent_keys_unique_api_key_index"
                   )

    drop table(:agent_keys)
  end
end
