defmodule Artifacts.Repo.Migrations.AddPublishingDomain do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:artifacts, primary_key: false) do
      add :id, :text, null: false, primary_key: true
      add :title, :text, null: false
      add :current_version, :bigint, null: false, default: 0
      add :archived_at, :utc_datetime_usec

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :organization_id,
          references(:organizations,
            column: :id,
            name: "artifacts_organization_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :restrict
          ),
          null: false
    end

    create table(:events, primary_key: false) do
      add :id, :bigserial, null: false, primary_key: true
      add :kind, :text, null: false
      add :data, :map, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :artifact_id,
          references(:artifacts,
            column: :id,
            name: "events_artifact_id_fkey",
            type: :text,
            prefix: "public",
            on_delete: :restrict
          ),
          null: false

      add :user_id,
          references(:users,
            column: :id,
            name: "events_user_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :restrict
          )

      add :agent_id,
          references(:agents,
            column: :id,
            name: "events_agent_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :restrict
          )

      add :harness_id,
          references(:harnesses,
            column: :id,
            name: "events_harness_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :restrict
          )
    end

    create constraint(:events, :events_actor_shape_check,
             check: """
               (user_id IS NOT NULL) <> (agent_id IS NOT NULL)
             AND (harness_id IS NULL OR user_id IS NOT NULL)

             """
           )

    execute("""
    CREATE FUNCTION events_refuse_change() RETURNS trigger AS $$
    BEGIN
      RAISE EXCEPTION 'events are append-only: % not allowed', TG_OP;
    END;
    $$ LANGUAGE plpgsql;
    """)

    execute("""
    CREATE TRIGGER events_refuse_change
    BEFORE UPDATE OR DELETE ON events
    FOR EACH ROW EXECUTE FUNCTION events_refuse_change();
    """)

    create table(:state_entries, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :path, :text, null: false
      add :value, :map, null: false
      add :updated_at, :utc_datetime_usec, null: false

      add :artifact_id,
          references(:artifacts,
            column: :id,
            name: "state_entries_artifact_id_fkey",
            type: :text,
            prefix: "public",
            on_delete: :restrict
          ),
          null: false
    end

    create unique_index(:state_entries, [:artifact_id, :path],
             name: "state_entries_unique_artifact_path_index"
           )

    alter table(:state_entries) do
      add :user_id,
          references(:users,
            column: :id,
            name: "state_entries_user_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :restrict
          )

      add :agent_id,
          references(:agents,
            column: :id,
            name: "state_entries_agent_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :restrict
          )

      add :harness_id,
          references(:harnesses,
            column: :id,
            name: "state_entries_harness_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :restrict
          )
    end

    create constraint(:state_entries, :state_entries_actor_shape_check,
             check: """
               (user_id IS NOT NULL) <> (agent_id IS NOT NULL)
             AND (harness_id IS NULL OR user_id IS NOT NULL)

             """
           )

    create table(:submissions, primary_key: false) do
      add :id, :bigserial, null: false, primary_key: true
      add :version, :bigint, null: false
      add :state, :map, null: false
      add :payload, :map

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :artifact_id,
          references(:artifacts,
            column: :id,
            name: "submissions_artifact_id_fkey",
            type: :text,
            prefix: "public",
            on_delete: :restrict
          ),
          null: false

      add :user_id,
          references(:users,
            column: :id,
            name: "submissions_user_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :restrict
          )

      add :agent_id,
          references(:agents,
            column: :id,
            name: "submissions_agent_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :restrict
          )

      add :harness_id,
          references(:harnesses,
            column: :id,
            name: "submissions_harness_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :restrict
          )
    end

    create constraint(:submissions, :submissions_actor_shape_check,
             check: """
               (user_id IS NOT NULL) <> (agent_id IS NOT NULL)
             AND (harness_id IS NULL OR user_id IS NOT NULL)

             """
           )

    execute("""
    CREATE FUNCTION submissions_refuse_change() RETURNS trigger AS $$
    BEGIN
      RAISE EXCEPTION 'submissions are append-only: % not allowed', TG_OP;
    END;
    $$ LANGUAGE plpgsql;
    """)

    execute("""
    CREATE TRIGGER submissions_refuse_change
    BEFORE UPDATE OR DELETE ON submissions
    FOR EACH ROW EXECUTE FUNCTION submissions_refuse_change();
    """)

    create table(:versions, primary_key: false) do
      add :number, :bigint, null: false, primary_key: true
      add :html, :text, null: false

      add :artifact_id,
          references(:artifacts,
            column: :id,
            name: "versions_artifact_id_fkey",
            type: :text,
            prefix: "public",
            on_delete: :restrict
          ), primary_key: true, null: false

      add :user_id,
          references(:users,
            column: :id,
            name: "versions_user_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :restrict
          )

      add :agent_id,
          references(:agents,
            column: :id,
            name: "versions_agent_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :restrict
          )

      add :harness_id,
          references(:harnesses,
            column: :id,
            name: "versions_harness_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :restrict
          )
    end

    create constraint(:versions, :versions_actor_shape_check,
             check: """
               (user_id IS NOT NULL) <> (agent_id IS NOT NULL)
             AND (harness_id IS NULL OR user_id IS NOT NULL)

             """
           )

    execute("""
    CREATE FUNCTION versions_refuse_change() RETURNS trigger AS $$
    BEGIN
      RAISE EXCEPTION 'versions are append-only: % not allowed', TG_OP;
    END;
    $$ LANGUAGE plpgsql;
    """)

    execute("""
    CREATE TRIGGER versions_refuse_change
    BEFORE UPDATE OR DELETE ON versions
    FOR EACH ROW EXECUTE FUNCTION versions_refuse_change();
    """)
  end

  def down do
    execute("""
    DROP TRIGGER IF EXISTS versions_refuse_change ON versions;
    """)

    execute("""
    DROP FUNCTION IF EXISTS versions_refuse_change();
    """)

    drop_if_exists constraint(:versions, :versions_actor_shape_check)

    drop constraint(:versions, "versions_harness_id_fkey")

    drop constraint(:versions, "versions_agent_id_fkey")

    drop constraint(:versions, "versions_user_id_fkey")

    drop constraint(:versions, "versions_artifact_id_fkey")

    drop table(:versions)

    execute("""
    DROP TRIGGER IF EXISTS submissions_refuse_change ON submissions;
    """)

    execute("""
    DROP FUNCTION IF EXISTS submissions_refuse_change();
    """)

    drop_if_exists constraint(:submissions, :submissions_actor_shape_check)

    drop constraint(:submissions, "submissions_harness_id_fkey")

    drop constraint(:submissions, "submissions_agent_id_fkey")

    drop constraint(:submissions, "submissions_user_id_fkey")

    drop constraint(:submissions, "submissions_artifact_id_fkey")

    drop table(:submissions)

    drop_if_exists constraint(:state_entries, :state_entries_actor_shape_check)

    drop constraint(:state_entries, "state_entries_harness_id_fkey")

    drop constraint(:state_entries, "state_entries_agent_id_fkey")

    drop constraint(:state_entries, "state_entries_user_id_fkey")

    drop constraint(:state_entries, "state_entries_artifact_id_fkey")

    alter table(:state_entries) do
      remove :harness_id
      remove :agent_id
      remove :user_id
    end

    drop_if_exists unique_index(:state_entries, [:artifact_id, :path],
                     name: "state_entries_unique_artifact_path_index"
                   )

    drop table(:state_entries)

    execute("""
    DROP TRIGGER IF EXISTS events_refuse_change ON events;
    """)

    execute("""
    DROP FUNCTION IF EXISTS events_refuse_change();
    """)

    drop_if_exists constraint(:events, :events_actor_shape_check)

    drop constraint(:events, "events_harness_id_fkey")

    drop constraint(:events, "events_agent_id_fkey")

    drop constraint(:events, "events_user_id_fkey")

    drop constraint(:events, "events_artifact_id_fkey")

    drop table(:events)

    drop constraint(:artifacts, "artifacts_organization_id_fkey")

    drop table(:artifacts)
  end
end
