import Config

# Two hostnames on one port: usetemi.art/usetemicontent.art in production,
# localhost/127.0.0.1 in dev. ArtifactsWeb.Plugs.HostRole reads these.
config :artifacts,
  app_host: "localhost",
  content_host: "127.0.0.1",
  # Only used by tests/dev that exercise register_with_google directly;
  # real Google sign-in needs GOOGLE_CLIENT_ID/SECRET/REDIRECT_URI set too.
  token_signing_secret: "dev_only_signing_secret_do_not_use_in_production_00000"

# Configure your database
config :artifacts, Artifacts.Repo,
  username: "postgres",
  password: "postgres",
  hostname: "localhost",
  database: "artifacts_dev",
  stacktrace: true,
  show_sensitive_data_on_connection_error: true,
  pool_size: 10

# For development, we disable any cache and enable
# debugging and code reloading.
#
# The watchers configuration can be used to run external
# watchers to your application. For example, we can use it
# to bundle .js and .css sources.
config :artifacts, ArtifactsWeb.Endpoint,
  # Binding to loopback ipv4 address prevents access from other machines.
  # Change to `ip: {0, 0, 0, 0}` to allow access from other machines.
  http: [ip: {127, 0, 0, 1}],
  # Endpoint-wide fallback only: the `/live` and `/socket` sockets each
  # carry their own stricter check_origin (ArtifactsWeb.Origins), scoped to
  # the app origin and the content origin respectively. This list is what
  # any future socket without its own override would fall back to.
  check_origin: ["//localhost", "//127.0.0.1"],
  code_reloader: true,
  debug_errors: true,
  secret_key_base: "MkaQakYjSKm4nW+T61qSmllCD3Ddhcsab9oc6K7vmfjxcEtJTkGDImbCOPIhRxTh",
  watchers: [
    esbuild: {Esbuild, :install_and_run, [:artifacts, ~w(--sourcemap=inline --watch)]}
  ]

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# Mix task:
#
#     mix phx.gen.cert
#
# Run `mix help phx.gen.cert` for more information.
#
# The `http:` config above can be replaced with:
#
#     https: [
#       port: 4001,
#       cipher_suite: :strong,
#       keyfile: "priv/cert/selfsigned_key.pem",
#       certfile: "priv/cert/selfsigned.pem"
#     ],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# Enable dev routes for dashboard and mailbox
config :artifacts, dev_routes: true

# Do not include metadata nor timestamps in development logs
config :logger, :default_formatter, format: "[$level] $message\n"

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20

# Initialize plugs at runtime for faster development compilation
config :phoenix, :plug_init_mode, :runtime

config :phoenix_live_view,
  # Include debug annotations and locations in rendered markup.
  # Changing this configuration will require mix clean and a full recompile.
  debug_heex_annotations: true,
  debug_attributes: true,
  # Enable helpful, but potentially expensive runtime checks
  enable_expensive_runtime_checks: true
