defmodule ArtifactsWeb.Endpoint do
  use Phoenix.Endpoint, otp_app: :artifacts

  # The session will be stored in the cookie and signed,
  # this means its contents can be read but not tampered with.
  # Set :encryption_salt if you would also like to encrypt it.
  @session_options [
    store: :cookie,
    key: "_artifacts_key",
    signing_salt: "4bHMC527",
    same_site: "Lax"
  ]

  # Both sockets check origin against ArtifactsWeb.Origins (an MFA, not a
  # literal list, since the app/content hosts are runtime-configured and
  # this module compiles once per release): the LiveView socket accepts
  # only the app origin, the content host's page socket only the content
  # origin — never the other one's.
  socket "/live", Phoenix.LiveView.Socket,
    websocket: [
      check_origin: {ArtifactsWeb.Origins, :app_origin?, []},
      connect_info: [session: @session_options]
    ],
    longpoll: [
      check_origin: {ArtifactsWeb.Origins, :app_origin?, []},
      connect_info: [session: @session_options]
    ]

  socket "/socket", ArtifactsWeb.ArtifactSocket,
    websocket: [
      check_origin: {ArtifactsWeb.Origins, :content_origin?, []},
      # Connect params carry the page token (`t`); Phoenix.Logger would
      # otherwise log them on every connect.
      log: false
    ]

  # Assigns conn.assigns.host_role (:app | :content) before anything else
  # runs, so every downstream plug and the router's per-pipeline
  # ArtifactsWeb.Plugs.RequireHost can rely on it.
  plug ArtifactsWeb.Plugs.HostRole

  # Serve at "/" the static files from "priv/static" directory.
  #
  # When code reloading is disabled (e.g., in production),
  # the `gzip` option is enabled to serve compressed
  # static files generated by running `phx.digest`.
  plug Plug.Static,
    at: "/",
    from: :artifacts,
    gzip: not code_reloading?,
    only: ArtifactsWeb.static_paths(),
    raise_on_missing_only: code_reloading?

  # Code reloading can be explicitly enabled under the
  # :code_reloader configuration of your endpoint.
  if code_reloading? do
    socket "/phoenix/live_reload/socket", Phoenix.LiveReloader.Socket
    plug Phoenix.LiveReloader
    plug Phoenix.CodeReloader
    plug Phoenix.Ecto.CheckRepoStatus, otp_app: :artifacts
  end

  plug Plug.RequestId
  plug Plug.Telemetry, event_prefix: [:phoenix, :endpoint]

  plug Plug.Parsers,
    parsers: [:urlencoded, :multipart, :json],
    pass: ["*/*"],
    json_decoder: Phoenix.json_library()

  plug Plug.MethodOverride
  plug Plug.Head
  plug Plug.Session, @session_options
  plug ArtifactsWeb.Router
end
